### ISSUE TITLE
Develop barebones UI

### ISSUE THREAD

**Issue by SaxyPandaBear** [SaxyPandaBear/TwitchSongRequests#12]
Requirements:
1. Be able to redirect to the UI, capturing the authorization code
2. Have the UI component emit the authorization code (have it as a log first. Can work from there)

Part 2 of the requirements begs the need for a server component for the UI to communicate with. Most likely some form of REST API that is stood up along with the main engine that is collecting all of the events from Twitch.

**Comment by ggenya132** [comment]
Small barebones UI in progress, would you like me to add the to repo or to keep it separate?

**Comment by SaxyPandaBear** [comment]
Closing this cause #17 clears it up. Thanks for working on it!
