### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by hotnasty** [SaxyPandaBear/TwitchSongRequests#144]
### Your Twitch username

digitalbob

**Comment by SaxyPandaBear** [comment]
I added you but I saw that you didn't sign up to let my service subscribe to Channel Point events from your channel. Make sure you go through all of the steps. You should see a "Subscribed Successfully" on the home page of the site if you are done and ready to be onboarded.

**Comment by SaxyPandaBear** [comment]
Because there are so few slots that I am allowed to give access to this project to, and considering that you didn't finish the onboarding, if I don't see  you finish the onboarding steps and start using the project in the next two weeks, I'm going to revoke it from my list of allowed users.

**Comment by hotnasty** [comment]
There was a “subscribed successfully” prompt after I gave it permissions to my twitch and Spotify the night that I requested access to the API. I would not have applied if I did not request access firstSent from my iPhoneOn Apr 30, 2023, at 4:43 PM, Andrew Huynh ***@***.***> wrote:﻿
Because there are so few slots that I am allowed to give access to this project to, and considering that you didn't finish the onboarding, if I don't see  you finish the onboarding steps and start using the project in the next two weeks, I'm going to revoke it from my list of allowed users.

**Comment by hotnasty** [comment]
[image: image.png]

**Comment by SaxyPandaBear** [comment]
Thanks for checking
