### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by rosethornttv** [SaxyPandaBear/TwitchSongRequests#163]
### Your Twitch username

rosethornttv  is my twitch user :D

**Comment by SaxyPandaBear** [comment]
Hi! Thanks for onboarding. In order to give access to your Spotify account, I need to know the email tied to that so I can allow list you. I DMed you on discord already. Thanks again!

**Comment by SaxyPandaBear** [comment]
Added. Thanks again (again)!
