### ISSUE TITLE
[Bug]: [Spotify Queue Up not working for me when i try adding songs to the Queue]

### ISSUE THREAD

**Issue by splinter1998** [SaxyPandaBear/TwitchSongRequests#170]
### What happened?

yesterday, i got whitelisted and when  i try  to put a song there in channel points my spotify didnt read it altho my spotify email ends with " .......224@gmail.com" any solution?
![image](https://github.com/SaxyPandaBear/TwitchSongRequests/assets/25197822/fd5f88dd-7289-4434-9031-ee1fe7cbf229)

### What part of the service is not working for you?

Subscribing to channel point rewards

**Comment by SaxyPandaBear** [comment]
Hey I will take a look tonight

**Comment by SaxyPandaBear** [comment]
Sorry had to go out of town on short notice. I don't have wifi until next week when I'm back. I want to minimize how much data I spend on hotspot

**Comment by splinter1998** [comment]
its fine no problem

**Comment by SaxyPandaBear** [comment]
OK I see logs that you unsubscribed, which is why there aren't any songs being queued. Please go through the onboarding steps again. You don't need to make a new GitHub issue or give me your email or anything again. Just follow the revoking access steps and start over. In my database it says I am not subscribed to events from your channel.

**Comment by splinter1998** [comment]
alright, for some reason the revoking access is bugged i cant do it even the subscribe thing do i need to remove the cookies?

**Comment by SaxyPandaBear** [comment]
Yeah I think you might have to. I will see what I can do to get around that in the future, though I'm not sure how you got into that state. Pretty sure when you revoked access it should have just cleared everything and expired the cookie.

**Comment by SaxyPandaBear** [comment]
@splinter1998 let me know if that worked for you

**Comment by splinter1998** [comment]
well, still bugged i cant hit the subscribe button i removed the cookies etc but still

**Comment by SaxyPandaBear** [comment]
Weird. Okay let me nuke your stuff in my database so you can try again - please remove cookies, etc again

**Comment by SaxyPandaBear** [comment]
Deleted your stuff from my db please try again from the top and let me know how it goes. Sorry that it

**Comment by splinter1998** [comment]
ok lemme try it again

**Comment by splinter1998** [comment]
ok i restarted the process

**Comment by SaxyPandaBear** [comment]
I want to try to do it all on my end, but I can't cause I need authorization from you :/ I checked my DB and you aren't subscribed there, and I also checked my actually application's subscriptions and didn't find you there. I don't know what the issue could be.

**Comment by splinter1998** [comment]
well atleast u tried man . i tried diffrent browser and still same problem

**Comment by splinter1998** [comment]
https://github.com/SaxyPandaBear/TwitchSongRequests/assets/25197822/8eade9f0-387e-40a6-8b02-4f72293318eb

heres the problem

**Comment by SaxyPandaBear** [comment]
OHHHH ok I see the problem. I had previously created a Twitch channel point reward on your account to use. Delete it.

**Comment by SaxyPandaBear** [comment]
```
{"level":"info","ts":"2023-06-07T23:26:35.422Z","caller":"api/eventsub.go:86","msg":"error occurred while creating Custom Reward | HTTP 400 | Bad Request | CREATE_CUSTOM_REWARD_DUPLICATE_REWARD"}
```

**Comment by SaxyPandaBear** [comment]
I had originally thought of adding some unique identifier to the custom reward I try to make, but I figured that is actually more work for most people - cause then everyone would have to go to their twitch account to update it. Idk how I missed this. Duh of course that's the problem. 😓

**Comment by splinter1998** [comment]
oh i see lemme try it

**Comment by splinter1998** [comment]
also btw, do i need to create another one or what?

**Comment by SaxyPandaBear** [comment]
At this point you just need to delete the custom reward that my service made, and then redo the steps

**Comment by splinter1998** [comment]
![image](https://github.com/SaxyPandaBear/TwitchSongRequests/assets/25197822/6ef5f9d8-55d3-40cd-9542-cf102be1a31c)

![image](https://github.com/SaxyPandaBear/TwitchSongRequests/assets/25197822/ffa9bd00-ab53-4821-8c78-c173542b8cbf)
well now it created channel points and for somereason still didnt work do i have to be whitelisted?

**Comment by SaxyPandaBear** [comment]
> "failed to publish: Player command failed: Premium required"}

**Comment by SaxyPandaBear** [comment]
The problem with the API I'm using is that in order to modify the player queue, the account needs to be on Spotify Premium

**Comment by splinter1998** [comment]
i see, well i need to subscribe to premium i'll do it this week and i'll tell you if its working or not thank youuu ❤️❤️

**Comment by SaxyPandaBear** [comment]
🙇 thank you so much for bearing with me this long

**Comment by splinter1998** [comment]
![image](https://github.com/SaxyPandaBear/TwitchSongRequests/assets/25197822/41f07d28-731d-4cb4-99e4-030ed6b2cd60)

it works perfectly thank u dude. ❤️❤️

**Comment by SaxyPandaBear** [comment]
WOO ok I'm so glad that it worked this time. Thanks for bearing with me for so long! Hope you enjoy it
