### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by Toxxxic2** [SaxyPandaBear/TwitchSongRequests#172]
### Your Twitch username

HighlyToxxxic

**Comment by Toxxxic2** [comment]
tthanks in advance <3

**Comment by SaxyPandaBear** [comment]
In my database it says you are not subscribed. Please go through all of the onboarding steps. Once you confirm you see that `Subscribed Successfully` page, I will check again

**Comment by SaxyPandaBear** [comment]
@Toxxxic2 can you check on this?

**Comment by Toxxxic2** [comment]
Ah right I see. Yeah I was hoping I could use chat commands to activate it also, but I'll contact you back when I get affiliate.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SaxyPandaBear** [comment]
Ah ok. Yeah I considered originally doing it as a chat bot, but thought that doing it with channel points would be more fun to build. Sorry about that!

**Comment by SaxyPandaBear** [comment]
Not affiliate, closing this from my queue to clean it up
