### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by thefirecar** [SaxyPandaBear/TwitchSongRequests#185]
### Your Twitch username

thefirecar

**Comment by SaxyPandaBear** [comment]
Hi I don't have an email associated with you for your Spotify account. I need that in order to add you to the list of authorized users for my service. Can you provide that? If you would rather do it over discord, I am saxypandabear there.

**Comment by thefirecar** [comment]
Hey i wrote you in DC.

**Comment by SaxyPandaBear** [comment]
Added you, thanks
