### ISSUE TITLE
[Bug]: [Describe the issue]

### ISSUE THREAD

**Issue by myhfie** [SaxyPandaBear/TwitchSongRequests#186]
### What happened?

The service worked at first (links queueing songs) but randomly stopped? I am not sure. twitch username is "myhf"

**Comment by SaxyPandaBear** [comment]
I'm not sure what you mean? I don't think I ever onboarded you.

**Comment by SaxyPandaBear** [comment]
Spotify will not accept requests for accounts that I don't manually allow access to, since their Terms of Service won't allow me to open up my project to a broader user base. I think you meant to make an onboarding request? I'll add you now and it should work.

**Comment by SaxyPandaBear** [comment]
Added you. I also turned on additional logging for my service in case I'm missing something obvious.

**Comment by myhfie** [comment]
strange, i could've sworn that i tested it the other day and it worked for me. it 100% works now, thank you!
