### ISSUE TITLE
[Bug]: [Describe the issue]

### ISSUE THREAD

**Issue by Todiezao** [SaxyPandaBear/TwitchSongRequests#188]
### What happened?

Something bad happened while using the service.

I think I did something wrong, the options no longer appear

![imagem_2023-06-26_080830090](https://github.com/SaxyPandaBear/TwitchSongRequests/assets/83521445/8391bf2b-e29b-480c-b869-7c3e174da6c3)

**Comment by SaxyPandaBear** [comment]
Please delete the custom reward that was created, revoke access and start over.
