### ISSUE TITLE
[Bug]: [Describe the issue]

### ISSUE THREAD

**Issue by Todiezao** [SaxyPandaBear/TwitchSongRequests#190]
### What happened?

Something bad happened while using the service.

![image](https://github.com/SaxyPandaBear/TwitchSongRequests/assets/83521445/ec7e5dab-a69b-48bd-a3b2-b63ee3b9b5a3)

**Comment by SaxyPandaBear** [comment]
What are you trying to do? You already authorized it. Did you try queuing a song?

**Comment by Todiezao** [comment]
oh really? let me try here

**Comment by Todiezao** [comment]
Every time I accessed "https://twitchsongrequests-production.up.railway.app" it appeared to connect spotify and twitch

but I didn't understand why, so I tried to connect spotify and that message appears.

this message appears when it has already been registered right?

Anyway, I still can't get it to work :(

**Comment by SaxyPandaBear** [comment]
You are supposed to go to your Twitch channel. Please watch the demo video.

**Comment by Todiezao** [comment]
I did the steps in the demo video, but it still didn't work...

**Comment by SaxyPandaBear** [comment]
```
{"level":"info","ts":"2023-06-26T14:00:55.500Z","caller":"api/callback.go:152","msg":"User 'Todiezao' submitted '[https://open.spotify.com/intl-pt/track/5XnfResHgNZC6VDwITDpTy?si=f34e3f91c52c4363'"](https://open.spotify.com/intl-pt/track/5XnfResHgNZC6VDwITDpTy?si=f34e3f91c52c4363%27%22);}
﻿{"level":"error","ts":"2023-06-26T14:00:55.622Z","caller":"api/callback.go:161","msg":"failed to publish","input":"[https://open.spotify.com/intl-pt/track/5XnfResHgNZC6VDwITDpTy?si=f34e3f91c52c4363","error":"Player](https://open.spotify.com/intl-pt/track/5XnfResHgNZC6VDwITDpTy?si=f34e3f91c52c4363%22,%22error%22:%22Player) command failed: Premium required"
```
You need Spotify Premium

**Comment by SaxyPandaBear** [comment]
@Todiezao are you planning on getting Spotify premium? If not, I will remove you from the list of allowed users, because Spotify Premium is required for this to work. The APIs that I call require premium subscription.

**Comment by SaxyPandaBear** [comment]
I removed your onboarding. Please make a new onboarding request if you want to use this and have Spotify premium.
