### ISSUE TITLE
[Bug]: [Describe the issue]

### ISSUE THREAD

**Issue by LaxQc** [SaxyPandaBear/TwitchSongRequests#192]
### What happened?

I did step by step what was told you gave me access but still wont work copied link as in video correctly redeemed channel points as in video but still never q's any song.

### What part of the service is not working for you?

Other (please describe above)

**Comment by SaxyPandaBear** [comment]
```
{"level":"error","ts":"2023-06-27T01:48:14.099Z","caller":"api/callback.go:161","msg":"failed to publish","input":"[https://open.spotify.com/track/2MbdDtCv5LUVjYy9RuGTgC?si=1e6e099ae0404701","error":"song](https://open.spotify.com/track/2MbdDtCv5LUVjYy9RuGTgC?si=1e6e099ae0404701%22,%22error%22:%22song) is too long. 227478 > 8000","
```
It looks like you set a max song duration and are trying to queue songs that are longer.

**Comment by LaxQc** [comment]
i put max song length to 9 mins or 8 I know those songs are not that long maybe 4 min max

**Comment by LaxQc** [comment]
nvm got it to work 
thanks for this bud great stuff

**Comment by SaxyPandaBear** [comment]
Thanks! Glad you got it to work. In case it wasn't clear, I think you tried to set the max to 8 minutes, but input 8 seconds.
