### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by TumitheGreat** [SaxyPandaBear/TwitchSongRequests#198]
### Your Twitch username

TumitheGreat

**Comment by SaxyPandaBear** [comment]
Thanks for the request. Right now, all of the spots are full so you'll have to wait a bit. I'm kind of busy this week but I will try to see who has actually gone through all of the onboarding later in the week to see if someone who was originally onboarded has revoked their accesses and I can remove them

**Comment by TumitheGreat** [comment]
Ah it's OK, you don't have to. I don't want to bother you, just wanted to
see if it would work. I don't stream as much as I used to, just wanted to
test if it works. I'll go revoke access today. Sorry about the confusion

**Comment by SaxyPandaBear** [comment]
It's no harm to me if you leave your access. There's a separate list of users who I have to manually maintain with Spotify to allowlist users that can actually use my project. What I meant was I want to cross reference that with people who I still get Twitch events from to see if any of them revoked access

**Comment by TumitheGreat** [comment]
I am a bit confused, do I have to do something?

**Comment by SaxyPandaBear** [comment]
No, you don't need to do anything. You can just wait

**Comment by TumitheGreat** [comment]
Ok, thanks for the clarification.

**Comment by SaxyPandaBear** [comment]
Thanks for your patience. I finally had time to clean up users that weren't using my service. Onboarded you
