### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by snKarma** [SaxyPandaBear/TwitchSongRequests#200]
### Your Twitch username

snKarma

**Comment by SaxyPandaBear** [comment]
So, it looks like in my db you successfully made one request in the past and I'm not entirely sure how. I'm onboarding your account now

**Comment by snKarma** [comment]
What do I have to do next so it works?

**Comment by SaxyPandaBear** [comment]
The onboarding step here is really just because Spotify only lets me allow 25 users to have access to my service. Everything other than the Spotify API access should be set up when you go through the onboarding steps. I added you, so it should all work now.

**Comment by snKarma** [comment]
Perfect thanks a lot
