### ISSUE TITLE
Document how to deploy the service yourself

### ISSUE THREAD

**Issue by SaxyPandaBear** [SaxyPandaBear/TwitchSongRequests#205]
This would have to come with removing any direct references to my site/API from the code, which I don't think there is.

**Comment by Karakazz** [comment]
There aren't any direct references in the code to your site as far as I can see aside from the html files in /pkg/site/
I think overall the easiest way to selfhost and deploy this is to make a docker-compose that builds from the dockerfile and passes the envs to the env.go. 
Though I think having a documentation to get the required env variables would be enough since the rest is self explanatory imo.

**Comment by darbdarb** [comment]
definitely would be nice to have documentation/a way to host this ur self  :)

**Comment by SaxyPandaBear** [comment]
Thanks for the feedback. I have been meaning to get to this for the longest time but I've been really busy with work and life. I probably won't iron this out to have clear docs until probably January since there's some steps that aren't going to be obvious for people who don't work with OAuth.

**Comment by Sacti00n** [comment]
Hello, is there any update to the documentation?

**Comment by SaxyPandaBear** [comment]
@Sacti00n no I haven't gotten to this yet. I have been super busy since November. I think the earliest I would get to this would be March/April. You could probably trace through and figure it out yourself, but the important external things you need to configure that I want to document are the OAuth setup for Twitch and Spotify, which allows the application to make API calls to those services.

**Comment by S4MARON** [comment]
Thank you, I appreciate your effort.  Do you have a ko-fi site or something?

**Comment by SaxyPandaBear** [comment]
Considering how many people are waiting in my onboarding queue, and how many people I keep revoking access for, I think I need to prioritize this so people can self host, and you have unlimited access for your own account - I deploy my project on Railway, which if you sign up with a credit card, they give you a $5 monthly credit, and this project for me at max number of users doesn't even come close to that credit value so it's essentially free self hosting. I'll see if I can document everything and produce a Railway template tomorrow
