### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by alysonrene** [SaxyPandaBear/TwitchSongRequests#220]
### Your Twitch username

alysanrene

**Comment by SaxyPandaBear** [comment]
Hi, I didn't get a Spotify email when you onboarded, and I need that to allowlist you on the Spotify side of this project. If you don't want to post it here, you can DM me on discord. I'm saxypandabear

**Comment by SaxyPandaBear** [comment]
Added you, thanks
