### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by AyoAshes** [SaxyPandaBear/TwitchSongRequests#222]
### Your Twitch username

AyoAshes

**Comment by SaxyPandaBear** [comment]
Hi thanks for going through the onboarding steps. I checked and didn't find an email associated with your Spotify account. I need that to allowlist you to start queueing songs. My discord is saxypandabear, you can DM it to me there

**Comment by SaxyPandaBear** [comment]
I just joined your stream and looks like you're using Songify so I'm just going to close this out
