### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by danthephenom** [SaxyPandaBear/TwitchSongRequests#223]
### Your Twitch username

DanThePhenom

**Comment by SaxyPandaBear** [comment]
Hi thanks for going through the onboarding steps. I checked and didn't find an email associated with your Spotify account. I need that to allowlist you to start queueing songs. My discord is saxypandabear, you can DM it to me there

**Comment by SaxyPandaBear** [comment]
Got confirmation that it worked. Closing this ticket out. Thanks for the quick response!
