### ISSUE TITLE
Hey there! I'd like an Onboarding Request pretty please :D

### ISSUE THREAD

**Issue by Sepulcherz** [SaxyPandaBear/TwitchSongRequests#238]
### Your Twitch username

SepulcherZ

**Comment by Sepulcherz** [comment]
Oh maybe the spots are full! Sorry about the mess haha

**Comment by SaxyPandaBear** [comment]
Did you go through all of the onboarding steps? I just checked and I think you're missing a step. I don't think I am currently able to receive Twitch events from your channel. Specifically step 5 from the sign up [guide](https://github.com/SaxyPandaBear/TwitchSongRequests#how-do-i-sign-up)
