### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by eric7string** [SaxyPandaBear/TwitchSongRequests#242]
### Your Twitch username

eric7string

**Comment by eric7string** [comment]
Not a problem, my email address is emn531@gmail.com, will also shoot you a friend request on discord, mine is eric7string

**Comment by SaxyPandaBear** [comment]
Thanks for the quick response! Added you. You should be good to go now. Let me know here or on discord if it doesn't work for you

**Comment by eric7string** [comment]
Seems to be all connected and working properly! Thank you so much, have been looking for a request system that queues up songs instead of just auto playing them forever and not only did you get exactly what I was after, but also gave it a very easy setup, and I appreciate it immensely!
