### ISSUE TITLE
[Bug]: Song Requests are no longer working

### ISSUE THREAD

**Issue by BaeliiBee** [SaxyPandaBear/TwitchSongRequests#244]
### What happened?

It worked for a few days then stopped. I'm not sure what really happened. songs are no longer queuing..

**Comment by SaxyPandaBear** [comment]
Hi, thanks for reaching out. I started looking at logs and don't see any logs from you. Maybe I need to add more logging but I don't see anything. I will keep looking tomorrow. I'm sorry it hasn't been working. One thing to check is if you are requesting songs that are tagged explicit by Spotify, but you haven't gone into your preferences on my site to allow explicit songs

**Comment by BaeliiBee** [comment]
I changed my password on facebook when i got a vpn and i sign into spotify through facebook. i think it started happening before that but i could be wrong. could that be the issue

**Comment by SaxyPandaBear** [comment]
No, that shouldn't be an issue as long as the email is the same. Can you try testing it out? I don't see anything wrong right now, and I know other streamers are currently queueing songs successfully so it's not an issue with the service as a whole

**Comment by BaeliiBee** [comment]
I just checked both with a song link and just the name of the song and neither worked. i checked and made sure the "Allow explicit songs?" box was checked as well

**Comment by SaxyPandaBear** [comment]
Okay, so it looks like Twitch says my subscription to your channel point alerts is `authorization_revoked`. I think I need to delete that, and then you have to do the "Subscribe" step again (which means you need to delete the custom reward again). I'm sorry. Let me fix that up right now

**Comment by SaxyPandaBear** [comment]
Alright, I deleted that from Twitch, and updated my database so it thinks you aren't subscribed anymore. You shouldn't have to go through all of the steps, I hope. You should:
1. Delete your existing channel point reward for song requests
2. Do step 5 for the onboarding
That _should_ be it.

**Comment by BaeliiBee** [comment]
It's working again. Thank you so much!

**Comment by SaxyPandaBear** [comment]
I'm glad it's working again! I don't know how to get around the issue you had, because Twitch reserved the right to just revoke access and I can't do anything about it, I don't think.
