### ISSUE TITLE
[Bug]: Song request no longer working

### ISSUE THREAD

**Issue by S4MARON** [SaxyPandaBear/TwitchSongRequests#250]
### What happened?

Song Request did work well in past but as of today it just stopped, i didnt changed anything

**Comment by SaxyPandaBear** [comment]
I don't see any errors on my end. I saw you queued up https://open.spotify.com/intl-de/track/4KiTVvoDILkT9vi8JhtfZm?si=e7824d4b6ad2448d and it looked successful.

**Comment by SaxyPandaBear** [comment]
The error I see is that you tried to queue a song with an explicit tag and you update your settings to allow that on my end.

**Comment by S4MARON** [comment]
Huh every song request that happened today was not placed in song queue, so tested it myself and it didn't worked for me neither. Because of that I checked the settings to fix it but it didn't

**Comment by S4MARON** [comment]
I tried again to request some songs and none were added in queue

**Comment by S4MARON** [comment]
Here I am again. I connected everything again it is working. Sorry for wasting time, even if I don't understand why it didnt work yesterday. btw the service is great thank you

**Comment by SaxyPandaBear** [comment]
Thanks for reaching out. I'm not really sure what the issue was. On my end, it all looked like it was working fine. Sorry for the inconvenience.
