### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by EngineerBean** [SaxyPandaBear/TwitchSongRequests#260]
### Your Twitch username

Beandownunder

**Comment by EngineerBean** [comment]
Will I got confirmation that this is active and able to be used?

**Comment by SaxyPandaBear** [comment]
Yeah, so right now I'm at capacity. In a couple weeks I'll check to see who hasn't been using it, hopefully free up capacity and then work on onboarding new people. When I close this issue and confirm that you're onboarded is when you'll know. If I had more time, I would work on writing a wiki and making a Railway template so you could self host, but I haven't had any time to

**Comment by EngineerBean** [comment]
No worries mate, thanks for letting me know what is going on. Self hosting would a great option and I would certainly consider it myself if you were to put a guide up on how to set it up. Anyways, appreciate all the work you have done to give streamers this feature and I look forward to making good use of what you have created.
