### ISSUE TITLE
Some songs are not adding in queue

### ISSUE THREAD

**Issue by simpsina** [SaxyPandaBear/TwitchSongRequests#261]
### What happened?

Hello! Its me again :(
Since we solved a problem with using requests, there appeared another one. Some of songs doesn't want to request (and I dont know why). For example, song Careless Whisper by George Michael can ALWAYS be requested by any of my chatters, but sometimes (in 70% cases) theres no song that my chatter requested (spotify definitely HAS this song - I checked by myself) even if he requested with link. In that case, chatter has their channel points back, i checked it too.

**Comment by SaxyPandaBear** [comment]
Hi thanks for reporting this. Sorry I've been really busy with work lately. I think I'll free up by like Sunday and I can try to look into this then. One thing you might want to check is if you allowed explicit songs or not. If you did, my next best guess is when I try to search for the song requested, I don't get a search result. I will look into it later though

**Comment by simpsina** [comment]
>One thing you might want to check is if you allowed explicit songs or not
I checked, and they were unallowed! Its all working now! Thanks for the help and sorry ><
