### ISSUE TITLE
[Bug]: Song Request stopped working

### ISSUE THREAD

**Issue by S4MARON** [SaxyPandaBear/TwitchSongRequests#264]
### What happened?

Am i still onboarded? Because since yesterday the song request no longer works. There were a bunch of song requests and none were automatically added to the queue. I just reconnected everything and it still doesn't seem to work.  Btw thank you for offering this service, its great

**Comment by snKarma** [comment]
Yeah it stopped working for me aswell, such a great upgrade for my stream hope it works soon again

**Comment by SaxyPandaBear** [comment]
Okay clearly I must be doing something wrong. I'm trying to remove streamers who haven't been using it in the past 30 days, but this makes me think that how I'm trying to determine that is not working.

**Comment by snKarma** [comment]
Yeah I prob had like 500 request past 30 days

**Comment by S4MARON** [comment]
I also had a bunch

**Comment by SaxyPandaBear** [comment]
so S4MARON is still onboarded, but snKarma isn't. I'll have to see why the songs aren't queueing for S4MARON. Separately, I need to figure out why my search for users to remove included snKarma when it shouldn't have.

**Comment by SaxyPandaBear** [comment]
```
successfully saved user preferences for 653821561

successfully deleted user 653821561
```

@S4MARON did you revoke access for yourself?

**Comment by SaxyPandaBear** [comment]
#265 might also be related to why they aren't working. It looks like there was a change in the Spotify API that broke a bunch of people that use it.

**Comment by S4MARON** [comment]
I revoked it myself and reconnected hoping to fix the problem haha ​​I hope I didn't make a mistake

**Comment by SaxyPandaBear** [comment]
So I probably have to do something to fix the twitch side of it for you, but also there is an issue with the Spotify API that is just breaking my project in general so I will deal with that once the other issue is fixed

**Comment by S4MARON** [comment]
Thank you, I appreciate your effort.  Do you have a ko-fi site or something?

**Comment by SaxyPandaBear** [comment]
I thought about making one but haven't bothered yet. In the discussions tab someone asked for something similar and I linked my paypal, but that's it so far. You also shouldn't feel obligated to pay me. This was just a fun project I wanted to do for a long time.

**Comment by snKarma** [comment]
Am I back onboarded and do I need to reconect everything? Thank you btw really nice for my stream

**Comment by simpsina** [comment]
I heard that spotify changed their API somehow. My song request stopped working too (same as other thing that helped me to integrate spotify to my stream for example my spotify badge, but i fixed it by reconnecting), reconnect didn't help :(

**Comment by SaxyPandaBear** [comment]
@snKarma no, not yet, sorry I'm on vacation so this isn't my main priority right now. 

@simpsina It's broken on my end, not yours. 

I know what I have to do to fix it immediately, but was hoping the library I use to connect to the Spotify API would have fixed the issue by now

**Comment by S4MARON** [comment]
its working again thx

**Comment by simpsina** [comment]
its all working now <3

**Comment by snKarma** [comment]
Thank you for fixing it, it sometimes stops working for a couple of hours, do you maybe know why and how to fix it? Also have a nice vacation! And dont stress about it enjoy your vacation

**Comment by SaxyPandaBear** [comment]
I'm not aware of anything that would break it for a couple hours. I can check to see if I find anything. Also I must have missed it but @snKarma I never removed you, so I think the issue you were having is the same as everyone else here. I thought I removed you. That's my bad for not double checking.

**Comment by SaxyPandaBear** [comment]
For you I see a couple different errors. 

```
failed to get valid token
error:"Post "https://accounts.spotify.com/api/token": context canceled"
```

```
input: "https://open.spotify.com/intl-de/artist/6nJEMDVNcq7fduXgk7EdGG"
```

The first one looks like just an intermittent issue from Spotify's side. Nothing I can really do about that other than adding retries on my end on failure, but that would require me changing a bunch of code cause I have to respond quickly to Twitch when I get an event. 

The second one seems like it should work, and is probably an issue on my end.

**Comment by SaxyPandaBear** [comment]
As far as I can tell, this particular issue is resolved. I created a new issue for myself to work on eventually that should help a little bit with the intermittent failures - #266
