### ISSUE TITLE
Onboarding Request

### ISSUE THREAD

**Issue by HeartlessDaze** [SaxyPandaBear/TwitchSongRequests#275]
### Your Twitch username

HeartlessDaze

**Comment by HeartlessDaze** [comment]
i revoked it cause it wasn't working properly but i reset it up again

**Comment by SaxyPandaBear** [comment]
If you revoked it, that might have messed up the twitch portion of it, but I guess we'll have to find out

**Comment by SaxyPandaBear** [comment]
added you, thanks!
